Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [100]:
import numpy as np
# Creating an empty array with shape (2, 2)
empty_array = np.empty((2, 2))
print(empty_array)


[[1. 0.]
 [0. 1.]]


2.Initialize an all one array with size 4X2.

In [101]:
ones_array = np.ones((4, 2))
print(ones_array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [102]:
fill_value_array = np.full((3, 3), 7, dtype=int)
print(fill_value_array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4.Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [103]:
existing_array = np.array([1, 2, 3, 4])
zeros_like_array = np.zeros_like(existing_array)
print(zeros_like_array)


[0 0 0 0]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [104]:
ones_like_array = np.ones_like(existing_array)
print(ones_like_array)


[1 1 1 1]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [105]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array is:", numpy_array)

Converted NumPy Array is: [1 2 3 4]


Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:
 1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}

In [106]:
import numpy as np

array = np.arange(10, 50)
print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [107]:
array_3x3 = np.arange(9).reshape(3, 3)
print(array_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [108]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}

In [109]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print(f"Mean of the array is: {mean_value}")


Mean of the array is: 0.4946987034537086


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [110]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print(f"Min: {min_value}, Max: {max_value}")


Min: 0.0008013415841383598, Max: 0.9965365975850242


 6. Create a zero array of size 10 and replace 5th element with 1

In [111]:
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [112]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


 8. Create a 2d array with 1 on border and 0 inside.

In [113]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print(border_array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [114]:
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


 Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy:
 1. Add the two array.

In [115]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
sum_array = np.add(x, y)
print(sum_array)


[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [116]:
subtract_array = np.subtract(x, y)
print(subtract_array)


[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [117]:
multiplied_array = x * 2
print(multiplied_array)


[[ 2  4]
 [ 6 10]]


 4. Find the square of each element of the array.

In [118]:
squared_array = np.square(x)
print(squared_array)


[[ 1  4]
 [ 9 25]]


 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [119]:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print(f"Dot product of v and w is: {dot_v_w}")
print(f"Dot product of x and v is: {dot_x_v}")
print(f"Dot product of x and y is: {dot_x_y}")


Dot product of v and w is: 219
Dot product of x and v is: [29 77]
Dot product of x and y is: [[19 22]
 [50 58]]


 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.

In [120]:
concatenate_x_y = np.concatenate((x, y), axis=0)
concatenate_v_w = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print(f"Concatenated x and y along rows:\n{concatenate_x_y}")
print(f"Concatenated v and w along columns:\n{concatenate_v_w}")


Concatenated x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenated v and w along columns:
[[ 9 11]
 [10 12]]


 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [121]:
try:
    concatenate_x_v = np.concatenate((x, v), axis=0)
    print(concatenate_x_v)
except Exception as e:
    print(f"Error: {e}")


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


 Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.


In [122]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])
I = np.eye(2)  # Identity matrix of size 2x2
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)
print("A * A^-1 = \n", result)
print("Identity Matrix I = \n", I)


A * A^-1 = 
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix I = 
 [[1. 0.]
 [0. 1.]]


 2. Prove AB= BA.

In [123]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB = \n", AB)
print("BA = \n", BA)
print("AB equals BA: ", np.allclose(AB, BA))  # Check if AB and BA are equal


AB = 
 [[23 13]
 [51 29]]
BA = 
 [[36 44]
 [13 16]]
AB equals BA:  False


 3. Prove (AB)T = BTAT.

In [124]:
AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("Transpose of AB = \n", AB_transpose)
print("B^T * A^T = \n", BT_AT)
print("(AB)^T equals B^T A^T: ", np.allclose(AB_transpose, BT_AT))  # Check if they are equal


Transpose of AB = 
 [[23 51]
 [13 29]]
B^T * A^T = 
 [[23 51]
 [13 29]]
(AB)^T equals B^T A^T:  True


 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9

In [125]:
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])  # Coefficient matrix
B_system = np.array([-1, -3, 9])
# Solve for X using the inverse method: X = A_inv * B
A_inv_system = np.linalg.inv(A_system)
X = np.dot(A_inv_system, B_system)
print("Solution of the system (x, y, z): ", X)


Solution of the system (x, y, z):  [ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

In [126]:
import numpy as np

# Coefficient matrix A (3x3)
A_system = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])

B_system = np.array([-1, -3, 9])

A_inv_system = np.linalg.inv(A_system)

X = np.dot(A_inv_system, B_system)

print("Solution of the system (x, y, z) is:", X)


Solution of the system (x, y, z) is: [ 2.  1. -2.]
